#!/bin/bash
# Build the LaTex book version

# copy the figures
rsync -a ~/ElementsOfDataScience/figs .

for NOTEBOOK in $@
do
    # remove image files generated by previous runs
    FIGS=${NOTEBOOK%.ipynb}_files
    echo "rm -f $FIGS/*"
    rm -f $FIGS/*

    # copy the notebook
    #echo "cp ../notebooks/$NOTEBOOK ."
    #cp ../notebooks/$NOTEBOOK .

    # add the header that generates PDF figures
    #echo "python add_header.py header_pdf.ipynb $NOTEBOOK"
    #python add_header.py header_pdf.ipynb $NOTEBOOK

    # remove cells with tags and solutions
    #echo "python remove_soln.py $NOTEBOOK"
    #python remove_soln.py $NOTEBOOK

    # convert notebooks to latex (to get PDF versions of figures)
    #echo "jupyter nbconvert --to latex $NOTEBOOK"
    #jupyter nbconvert --execute --to latex $NOTEBOOK

    # copy the notebook again
    echo "cp ../notebooks/$NOTEBOOK ."
    cp ../notebooks/$NOTEBOOK .

    # add the header that generates LaTeX tables
    echo "python add_header.py header_latex.ipynb $NOTEBOOK"
    python add_header.py header_latex.ipynb $NOTEBOOK

    # remove cells with solutions
    echo "python remove_soln.py $NOTEBOOK"
    python remove_soln.py $NOTEBOOK

    # run tests to generate LaTeX tables and PNG figures
    # and overwrite the notebook
    pytest --nbmake --overwrite $NOTEBOOK

    # conda install -c conda-forge jupyter_contrib_nbextensions

    # FLAGS="--InlineBackend.figure_format=png --execute"

    # remove cells with remove-cell tag
    # (actually remove source and outputs)
    # We have to keep the cell;
    # otherwise it throws off the figuring numbering
    echo "python remove_cells.py $NOTEBOOK"
    python remove_cells.py $NOTEBOOK

    # convert notebooks to markdown
    echo "jupyter nbconvert --to markdown $NOTEBOOK"
    jupyter nbconvert --to markdown $NOTEBOOK

    # convert markdown to LaTeX
    FLAGS="--listings --top-level-division=chapter"
    MDFILE=${NOTEBOOK%.ipynb}.md
    TEXFILE=${NOTEBOOK%.ipynb}.tex
    echo "pandoc $FLAGS -s $MDFILE -o $TEXFILE"
    pandoc $FLAGS -s $MDFILE -o $TEXFILE

    # remove front and backmatter from the chapters
    # (and make a few text substitutions)
    echo "python split.py $TEXFILE"
    python split.py $TEXFILE

done
